<a href="https://colab.research.google.com/github/Manhatai/Data_Science_Bootcamp/blob/main/NumPy_podstawy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###Np Array wprowadzenie

In [2]:
import numpy as np
np.__version__

'1.23.5'

In [4]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_CopyMode', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__getattr__', '__git_version__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_distributor_in

In [ ]:
help(np.array)

In [6]:
x = np.array([1, 3])
x

array([1, 3])

In [7]:
print(x)

[1 3]


In [9]:
type(x) # sprawdzenie typu tablicy

numpy.ndarray

In [10]:
x.ndim #wymiary tablicy

1

In [11]:
x.shape # kształt tablicy (2 elementy = 2)

(2,)

In [12]:
x.size # liczba elementów w tablity

2

In [14]:
x.dtype # typ danych

dtype('int64')

In [17]:
x = np.array([1.3, 2.3, 1.4])
print(x)

[1.3 2.3 1.4]


In [19]:
x.dtype

dtype('float64')

In [20]:
x = np.array([[1,2], [-3, 1]])
x

array([[ 1,  2],
       [-3,  1]])

In [21]:
x.ndim # dwuwymiarowa tablica więc 2

2

In [22]:
x.shape # 2x2

(2, 2)

In [24]:
x = np.array([[1,2,3], [4,2,1]])
print(x)

[[1 2 3]
 [4 2 1]]


In [25]:
x.shape # dwa wiersze, trzy kolumny (2x3)

(2, 3)

In [32]:
x = np.array(
    [[[4, 3, 1],
      [3, 1, 2]],

    [[4, 1, 3],
      [4, 2, 1]],

     [[3, 2, 1],
      [4, 3, 2]]]
)
x

array([[[4, 3, 1],
        [3, 1, 2]],

       [[4, 1, 3],
        [4, 2, 1]],

       [[3, 2, 1],
        [4, 3, 2]]])

In [33]:
x.ndim # trójwymiarowa tablica, więc 3

3

In [34]:
x.shape # trzy tablice, dwa wiersze, trzy kolumny (2x2x3)

(3, 2, 3)

###Typy danych

In [43]:
A = np.array([1, 2, 3])
A.dtype

dtype('int64')

In [40]:
A = np.array([1, 2, 3], dtype='float') # Zmiana na inne typy danych
A.dtype

dtype('float64')

In [39]:
A

array([1., 2., 3.])

In [41]:
A = np.array([1, 2, 3], dtype='complex')
A.dtype

dtype('complex128')

In [42]:
A

array([1.+0.j, 2.+0.j, 3.+0.j])

In [44]:
A = np.array([1, 2, 3], dtype='int')
A.dtype

dtype('int64')

In [45]:
A

array([1, 2, 3])

In [46]:
A = np.array([1.1, 2.7, 3.5], dtype='int') # dtype może przez przypadek uciąć dane
A.dtype

dtype('int64')

In [47]:
A

array([1, 2, 3])

In [49]:
A = np.array([True, False])
A.dtype

dtype('bool')

In [51]:
A = np.array([24, 120, 230], dtype=np.int8) # Używane w computer vision!
A.dtype

dtype('int8')

In [52]:
A = np.array([24, 120, 230], dtype=np.uint8) # Używane w computer vision!
A.dtype

dtype('uint8')

###Tworzenie tablic

In [53]:
np.zeros(shape=(4, 10)) # zeros - same zera, shape - 4 wiersze, 10 kolumn

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [54]:
np.zeros(shape=(4, 10), dtype='int') # przydatne do tworzenia zdjęć x na x pikseli z czarnym tłem

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [56]:
np.ones(shape=(5, 5), dtype='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [57]:
np.full(shape=(10,10), fill_value=4, dtype='int') # wypełnia liczbę daną wartością 'fill_value'

array([[4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4]])

In [59]:
np.arange(100) # tworzy tablicę od 0 o podanej ilości liczb

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [61]:
np.arange(start=10, stop=100, step=10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [62]:
np.arange(start=100, stop=10, step=-10) # końcowy element nie zostaje włączony, tak jak powyżej

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [63]:
np.arange(start=0, stop=1, step=0.05)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [66]:
np.linspace(start = 0, stop = 1, num = 10) # generuje 'num' losowych elementów z przedziału

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [67]:
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [68]:
A.reshape((3, 5)) # zmienia ułożenie tablicy wedle życzenia

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [72]:
A.reshape((3, -1)) # Gdy wpiszemy -1, python sam wybiera optymalną liczbę wierszy/kolumn. Jedna wartosc musi byc znana

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [73]:
A.reshape((-1, 3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

### Podstawowe operacje na tablicach

In [74]:
A = np.array([3, 1, 4, 2])
B = np.array([3, -1, 3, 2])
print(A)
print(B)

[3 1 4 2]
[ 3 -1  3  2]


In [75]:
A + B # zasada taka sama jak w macierzach, rozmiar tablic musi sie zgadzać

array([6, 0, 7, 4])

In [76]:
A - B

array([0, 2, 1, 0])

In [77]:
A * B

array([ 9, -1, 12,  4])

In [78]:
A / B # tablica nie może zawierać 0!!

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [84]:
np.add(A, B)

array([6, 0, 7, 4])

In [85]:
np.subtract(A, B)

array([0, 2, 1, 0])

In [86]:
np.multiply(A, B)

array([ 9, -1, 12,  4])

In [ ]:
np.divide(A, B)

In [79]:
A + 3 # W tak prosty sposób można dodawać/odejmować rzeczy z tablicy

array([6, 4, 7, 5])

In [80]:
2 * A

array([6, 2, 8, 4])

In [81]:
abs(A)

array([3, 1, 4, 2])

In [82]:
A + 3*B

array([12, -2, 13,  8])

In [89]:
x = np.array([[1,3], [-2, 0]])
y = np.array([[6,0], [-1,2]])
print(x, '\n')
print(y)

[[ 1  3]
 [-2  0]] 

[[ 6  0]
 [-1  2]]


In [91]:
x * y

array([[6, 0],
       [2, 0]])

In [92]:
np.dot(x, y) # mnożenie macierzowe

array([[  3,   6],
       [-12,   0]])

In [93]:
y.dot(y) # oczywiście mnożenie macierzy nie jest przemienne

array([[ 6, 18],
       [-5, -3]])

In [94]:
x @ Y

array([[  3,   6],
       [-12,   0]])