<a href="https://colab.research.google.com/github/Manhatai/Data_Science_Bootcamp/blob/main/Algebra_liniowa_przypomnienie.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Norma wektora i odleglosc punktów

In [1]:
import numpy as np

In [5]:
v1 = np.array([-1, 4]) # przykładowa macierz 1x2
v1

array([-1,  4])

In [7]:
np.linalg.norm(v1) # liczenie normy wektorowej w przestrzeni R^2

4.123105625617661

In [8]:
v2 = np.array([-10, 10, 13]) # Długość wektora w przestrzeni R^3 (norma euklidesowa)
np.linalg.norm(v2)

19.209372712298546

### Odległość dwóch punktów na płaszczyźnie

In [10]:
p = np.array([3, 0]) # R^2
q = np.array([0, 4])

np.linalg.norm(p - q) # Liczy odległość dwóch punktów na płaszczyźnie

5.0

In [11]:
p = np.array([3, 0, 1]) # R^3
q = np.array([0, 4, 2])

np.linalg.norm(p - q)

5.0990195135927845

### Mnożenie macierzy

In [12]:
# Aby móc mnożyć macierze, liczba kolumn lewej macierzy musi zgadzać się z liczbą wierszy prawej (przypominajka)

In [16]:
X = np.array([[5, 3], [3, 9]])
Y = np.array([[1], [-1]])
print(X,'\n')
print(Y)

[[5 3]
 [3 9]] 

[[ 1]
 [-1]]


In [20]:
Z = np.dot(X, Y) # Mnożenie macierzy
Z

array([[ 2],
       [-6]])

In [19]:
Z.shape # Kształt macierzy (2 wiersze 1 kolumna)

(2, 1)

In [21]:
Z = np.dot(Y, X) # Nie można pomnożyć, ponieważ kolumny lewej macierzy nie zgadzają się z wierszami prawej
Z

ValueError: shapes (2,1) and (2,2) not aligned: 1 (dim 1) != 2 (dim 0)

In [22]:
X = np.array([[2, -1, 3],
              [3, 1, 0]])
Y = np.array([[2, 1, -1],
              [0, -1, 2],
              [3, 2, 0]])
print(X,'\n')
print(Y)

[[ 2 -1  3]
 [ 3  1  0]] 

[[ 2  1 -1]
 [ 0 -1  2]
 [ 3  2  0]]


In [23]:
np.dot(X, Y) # Macierz wynikowa będzie rozmiaru wierszów pierwszej macierzy i kolumn drugiej macierzy

array([[13,  9, -4],
       [ 6,  2, -1]])

### Wyznacznik macierzy

In [27]:
A = np.array([[2, 4],
              [-1, 3]])
A

array([[ 2,  4],
       [-1,  3]])

In [26]:
round(np.linalg.det(A)) # Wyznacznik macierzy

10

### Ślad macierzy

In [30]:
A = np.array([[2, 4],
              [-1, 3]])
np.trace(A) # ślad macierzy

5

### Macierz jednostkowa

In [31]:
np.eye(5, dtype='int') # macierz jednostkowa (eye)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

### Macierz odwrotna

In [32]:
A

array([[ 2,  4],
       [-1,  3]])

In [33]:
B = np.linalg.inv(A)
B

array([[ 0.3, -0.4],
       [ 0.1,  0.2]])

In [36]:
np.set_printoptions(precision=4, suppress=True)

np.dot(A, B)

array([[1., 0.],
       [0., 1.]])

In [37]:
np.dot(B, A)

array([[ 1., -0.],
       [ 0.,  1.]])

### Macierz transponowana

In [38]:
# Zamiana wierszy na kolumny

In [39]:
A

array([[ 2,  4],
       [-1,  3]])

In [40]:
np.transpose(A)

array([[ 2, -1],
       [ 4,  3]])

In [41]:
A.T

array([[ 2, -1],
       [ 4,  3]])

### Rozwiązywanie układów równań

In [43]:
A = np.array([[2, 4],   # W przypadku gdy byłaby to macierz nie kwadratowa, następuje wzór
              [1, -1]]) # A * B = X. Jeśli mamy macierz kwadratową, musimy najpierw ją odwrócić,
B = np.array([[10],     # aby uzyskać prawidłowy wynik x i y.
              [-1]])
print(A,'\n')
print(B)

[[ 2  4]
 [ 1 -1]] 

[[10]
 [-1]]


In [46]:
A_inv = np.linalg.inv(A)
X = np.dot(A_inv, B)
X

array([[1.],
       [2.]])

In [47]:
X.shape

(2, 1)