<a href="https://colab.research.google.com/github/Manhatai/Data_Science_Bootcamp/blob/main/NumPy_podstawy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###Np Array wprowadzenie

In [2]:
import numpy as np
np.__version__

'1.23.5'

In [ ]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_CopyMode', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__getattr__', '__git_version__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_distributor_in

In [ ]:
help(np.array)

In [ ]:
x = np.array([1, 3])
x

array([1, 3])

In [ ]:
print(x)

[1 3]


In [ ]:
type(x) # sprawdzenie typu tablicy

numpy.ndarray

In [ ]:
x.ndim #wymiary tablicy

1

In [ ]:
x.shape # kształt tablicy (2 elementy = 2)

(2,)

In [ ]:
x.size # liczba elementów w tablity

2

In [ ]:
x.dtype # typ danych

dtype('int64')

In [ ]:
x = np.array([1.3, 2.3, 1.4])
print(x)

[1.3 2.3 1.4]


In [ ]:
x.dtype

dtype('float64')

In [ ]:
x = np.array([[1,2], [-3, 1]])
x

array([[ 1,  2],
       [-3,  1]])

In [ ]:
x.ndim # dwuwymiarowa tablica więc 2

2

In [ ]:
x.shape # 2x2

(2, 2)

In [ ]:
x = np.array([[1,2,3], [4,2,1]])
print(x)

[[1 2 3]
 [4 2 1]]


In [ ]:
x.shape # dwa wiersze, trzy kolumny (2x3)

(2, 3)

In [ ]:
x = np.array(
    [[[4, 3, 1],
      [3, 1, 2]],

    [[4, 1, 3],
      [4, 2, 1]],

     [[3, 2, 1],
      [4, 3, 2]]]
)
x

array([[[4, 3, 1],
        [3, 1, 2]],

       [[4, 1, 3],
        [4, 2, 1]],

       [[3, 2, 1],
        [4, 3, 2]]])

In [ ]:
x.ndim # trójwymiarowa tablica, więc 3

3

In [ ]:
x.shape # trzy tablice, dwa wiersze, trzy kolumny (2x2x3)

(3, 2, 3)

###Typy danych

In [ ]:
A = np.array([1, 2, 3])
A.dtype

dtype('int64')

In [ ]:
A = np.array([1, 2, 3], dtype='float') # Zmiana na inne typy danych
A.dtype

dtype('float64')

In [ ]:
A

array([1., 2., 3.])

In [ ]:
A = np.array([1, 2, 3], dtype='complex')
A.dtype

dtype('complex128')

In [ ]:
A

array([1.+0.j, 2.+0.j, 3.+0.j])

In [ ]:
A = np.array([1, 2, 3], dtype='int')
A.dtype

dtype('int64')

In [ ]:
A

array([1, 2, 3])

In [ ]:
A = np.array([1.1, 2.7, 3.5], dtype='int') # dtype może przez przypadek uciąć dane
A.dtype

dtype('int64')

In [ ]:
A

array([1, 2, 3])

In [ ]:
A = np.array([True, False])
A.dtype

dtype('bool')

In [ ]:
A = np.array([24, 120, 230], dtype=np.int8) # Używane w computer vision!
A.dtype

dtype('int8')

In [ ]:
A = np.array([24, 120, 230], dtype=np.uint8) # Używane w computer vision!
A.dtype

dtype('uint8')

###Tworzenie tablic (WAŻNE)

In [ ]:
np.zeros(shape=(4, 10)) # zeros - same zera, shape - 4 wiersze, 10 kolumn

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
np.zeros(shape=(4, 10), dtype='int') # przydatne do tworzenia zdjęć x na x pikseli z czarnym tłem

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
np.ones(shape=(5, 5), dtype='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
np.full(shape=(10,10), fill_value=4, dtype='int') # wypełnia liczbę daną wartością 'fill_value'

array([[4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4]])

In [ ]:
np.arange(100) # tworzy tablicę od 0 o podanej ilości liczb

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [ ]:
np.arange(start=10, stop=100, step=10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
np.arange(start=100, stop=10, step=-10) # końcowy element nie zostaje włączony, tak jak powyżej

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [ ]:
np.arange(start=0, stop=1, step=0.05)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [ ]:
np.linspace(start = 0, stop = 1, num = 10) # generuje 'num' losowych elementów z przedziału

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [ ]:
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
A.reshape((3, 5)) # zmienia ułożenie tablicy wedle życzenia

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
A.reshape((3, -1)) # Gdy wpiszemy -1, python sam wybiera optymalną liczbę wierszy/kolumn. Jedna wartosc musi byc znana

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
A.reshape((-1, 3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

### Podstawowe operacje na tablicach (WAŻNE)

In [ ]:
A = np.array([3, 1, 4, 2])
B = np.array([3, -1, 3, 2])
print(A)
print(B)

[3 1 4 2]
[ 3 -1  3  2]


In [ ]:
A + B # zasada taka sama jak w macierzach, rozmiar tablic musi sie zgadzać

array([6, 0, 7, 4])

In [ ]:
A - B

array([0, 2, 1, 0])

In [ ]:
A * B

array([ 9, -1, 12,  4])

In [ ]:
A / B # tablica nie może zawierać 0!!

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [ ]:
np.add(A, B)

array([6, 0, 7, 4])

In [ ]:
np.subtract(A, B)

array([0, 2, 1, 0])

In [ ]:
np.multiply(A, B)

array([ 9, -1, 12,  4])

In [ ]:
np.divide(A, B)

In [ ]:
A + 3 # W tak prosty sposób można dodawać/odejmować rzeczy z tablicy

array([6, 4, 7, 5])

In [ ]:
2 * A

array([6, 2, 8, 4])

In [ ]:
abs(A)

array([3, 1, 4, 2])

In [ ]:
A + 3*B

array([12, -2, 13,  8])

In [ ]:
x = np.array([[1,3], [-2, 0]])
y = np.array([[6,0], [-1,2]])
print(x, '\n')
print(y)

[[ 1  3]
 [-2  0]] 

[[ 6  0]
 [-1  2]]


In [ ]:
x * y

array([[6, 0],
       [2, 0]])

In [ ]:
np.dot(x, y) # mnożenie macierzowe

array([[  3,   6],
       [-12,   0]])

In [ ]:
y.dot(y) # oczywiście mnożenie macierzy nie jest przemienne

array([[ 6, 18],
       [-5, -3]])

In [ ]:
x @ Y

array([[  3,   6],
       [-12,   0]])

### Liczby pseudolosowe

In [ ]:
np.random.seed(0) # Ziarno ustalone, aby liczby losowe nie zmieniały się za każdym razem

In [ ]:
np.random.randn() # Losowy rozkład normalny

1.764052345967664

In [ ]:
np.random.randn(10) # 10 losowych elementow z ukladu normalnego (0 - średnia, 1 - odchylenie standardowe)

array([ 1.45427351,  0.76103773,  0.12167502,  0.44386323,  0.33367433,
        1.49407907, -0.20515826,  0.3130677 , -0.85409574, -2.55298982])

In [ ]:
np.random.randn(10, 4) # 10 - liczba wierszy, 4 - liczba kolumn

array([[ 0.6536186 ,  0.8644362 , -0.74216502,  2.26975462],
       [-1.45436567,  0.04575852, -0.18718385,  1.53277921],
       [ 1.46935877,  0.15494743,  0.37816252, -0.88778575],
       [-1.98079647, -0.34791215,  0.15634897,  1.23029068],
       [ 1.20237985, -0.38732682, -0.30230275, -1.04855297],
       [-1.42001794, -1.70627019,  1.9507754 , -0.50965218],
       [-0.4380743 , -1.25279536,  0.77749036, -1.61389785],
       [-0.21274028, -0.89546656,  0.3869025 , -0.51080514],
       [-1.18063218, -0.02818223,  0.42833187,  0.06651722],
       [ 0.3024719 , -0.63432209, -0.36274117, -0.67246045]])

In [3]:
np.random.randint(10) # losowa liczba między 0 a 10

5

In [5]:
np.random.randint(low=10, high=101) # losowa liczba między 10 a 101

60

In [6]:
np.random.randint(low=10, high=101, size=10) # 10 losowych liczb między 10 a 101

array([58, 54, 90, 98, 64, 45, 83, 40, 33, 14])

In [10]:
np.random.choice([4, 2, 1, 4]) # randomowy element z listy

4

In [12]:
np.random.choice(['python', 'java', 'sql']) # działa także na stringach

'java'

In [14]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.random.shuffle(data)
data

array([5, 7, 8, 3, 9, 4, 6, 1, 2, 0])

### Podstawowe funkcje w NumPy (WAŻNE)

In [18]:
np.exp(1) # Bardzo ważna funkcja w uczeniu maszynowym (stała e^2) (stała logarytmu naturalnego)

2.718281828459045

In [19]:
np.sqrt(9)

3.0

In [20]:
np.all([2, 3, 1]) # bada każdy element i sprawdza czy zwraca wartość logiczną true/false

True

In [23]:
np.any([1, 2, 1]) # sprawdza czy jakikolwiek obiekt jest prawdą

True

In [26]:
np.any([0,0,0])

False

In [30]:
bool(1.3)

True

In [34]:
A = np.random.rand(5)
A

array([0.8419557 , 0.2473544 , 0.14432376, 0.84131306, 0.72282353])

In [36]:
np.argmax(A) # zwraca największą wartość z przedziału

0

In [37]:
A[np.argmax(A)] # wycięcie wartości z przedziału

0.8419556969557124

In [39]:
np.argmin(A) # zwraca najmniejszą wartość z przedziału

2

In [40]:
np.argsort(A) # zwraca indeksami wartość od najmniejszej do największej (przydatne np do zwracania 2-3 najbardziej prawdopodobnych klas)

array([2, 1, 4, 3, 0])

In [41]:
np.max(A)

0.8419556969557124

In [42]:
np.min(A)

0.14432376073586917

In [43]:
np.mean(A) # średnia

0.5595540895276422

In [44]:
np.median(A)

0.7228235254752067

In [45]:
np.std(A)

0.30188758473724747

### Indeksowanie (WAŻNE)

In [47]:
A = np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [48]:
# A[index], A[start:stop], A[:stop], A[start:] #zwracanie elementów poprzez indeksowanie

In [49]:
A[2]

2

In [50]:
A[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [51]:
A[:2]

array([0, 1])

In [52]:
A[[0, 2]] # Wycinamy indeks 0 i indeks 2

array([0, 2])

In [54]:
A[-1] # pierwszy od konca element

19

In [55]:
A[10:15]

array([10, 11, 12, 13, 14])

In [57]:
A = A.reshape(4, 5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [59]:
A[0] # wycinamy cały pierwszy wiersz

array([0, 1, 2, 3, 4])

In [60]:
A[1] # wycinamy cały drugi wiersz

array([5, 6, 7, 8, 9])

In [61]:
A[:, 0] # wycinamy pierwszą kolumnę

array([ 0,  5, 10, 15])

In [62]:
A[:, 1] # wycinamy drugą kolumnę

array([ 1,  6, 11, 16])

In [63]:
A[:, -1] # wycinamy pierwszą od końca kolumnę

array([ 4,  9, 14, 19])

In [67]:
A[2, 4] # A[indeks_wierszu, indeks_kolumny], czyli wycinanie konkretnego elementu

14

In [69]:
A[1:3, 1:4] # Wycinanie fragmentów tablicy

array([[ 6,  7,  8],
       [11, 12, 13]])

In [72]:
A[1, 2] = 14 # Zmiana elementu w tabeli
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

### Iteracja po tablicach (WAŻNE)

In [73]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [75]:
for row in A: # iterowanie po wierszu
  print(row)

[0 1 2 3 4]
[ 5  6 14  8  9]
[10 11 12 13 14]
[15 16 17 18 19]


In [80]:
for row in A: # iterowanie po konkretnym indeksie z każdego wiersza
  print(row[0])

0
5
10
15


In [81]:
for row in A:
  print(row[:3])

[0 1 2]
[ 5  6 14]
[10 11 12]
[15 16 17]


In [82]:
for item in A.flat: # iterujemy po każdym elemencie tablicy
  print(item)

0
1
2
3
4
5
6
14
8
9
10
11
12
13
14
15
16
17
18
19


### Zmiana rozmiaru tablic

In [83]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [84]:
A.shape

(4, 5)

In [85]:
A.reshape(5, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6, 14],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [86]:
A.ravel() # wypłaszczanie danych w tablicy

array([ 0,  1,  2,  3,  4,  5,  6, 14,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [87]:
A.T # Transponowanie macierzy (zmienianie wierszy na kolumny i kolumny na wiersze)

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2, 14, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

### Maski logiczne

In [109]:
A = np.arange(start=-10, stop=10, step=0.5)
A

array([-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ,  -6.5,  -6. ,
        -5.5,  -5. ,  -4.5,  -4. ,  -3.5,  -3. ,  -2.5,  -2. ,  -1.5,
        -1. ,  -0.5,   0. ,   0.5,   1. ,   1.5,   2. ,   2.5,   3. ,
         3.5,   4. ,   4.5,   5. ,   5.5,   6. ,   6.5,   7. ,   7.5,
         8. ,   8.5,   9. ,   9.5])

In [110]:
A.reshape(10, -1)

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [111]:
A > 0 # To ta maska

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True])

In [112]:
A[A > 0] # Tylko elementy dodatnie

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [114]:
np.bitwise_and(A > -5, A < 5) # Zwraca maskę gdzie oba warunki są spełnione

array([False, False, False, False, False, False, False, False, False,
       False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False, False, False, False, False, False,
       False, False, False, False])

In [115]:
np.bitwise_or(A < -5, A > 5)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True])